---
# Copyright 2019, Internet Solutions.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Set fact for automatically enabling networks (IPv4)
  set_fact:
    bird_ipv4_enabled: "{{ ansible_default_ipv4 is defined | bool }}"
  when:
    - "bird_ipv4_enabled == 'detect'"
  tags:
    - bird-config
    - bird-init

- name: Set fact for automatically enabling networks (IPv6)
  set_fact:
    bird_ipv6_enabled: >-
      {{ (ansible_default_ipv6 is defined
         and ansible_default_ipv6['scope'] is defined
         and ansible_default_ipv6['scope'] == 'global') | bool }}
  when:
    - "bird_ipv6_enabled == 'detect'"
  tags:
    - bird-config
    - bird-init

- name: Ensure log file exists and is owned correctly
  file:
    path: "{{ bird_syslog_location }}"
    owner: bird
    group: bird
    mode: '0664'
    state: touch
  tags:
    - bird-config

- name: Drop bird configuration files
  template:
    src: bird-conf.j2
    dest: "{{ item.config_file }}"
    owner: "root"
    group: "root"
    mode: "0644"
  register: bird_results
  when: "item.enabled | bool"
  loop: "{{ bird_configs }}"
  tags:
    - bird-config

- name: Drop bird ibgp template
  template:
    src: bird-bgp-rr-template.j2
    dest: "/etc/bird.rr.bgp.template"
    owner: "root"
    group: "root"
    mode: "0644"
  register: bird_results_rr
  loop: "{{ query('dict', rr) }}"
  tags:
    - bird-config

- name: Drop bird ebgp template
  template:
    src: bird-bgp-rs-template.j2
    dest: "/etc/bird.rs.bgp.template"
    owner: "root"
    group: "root"
    mode: "0644"
  register: bird_results_rs
  loop: "{{ query('dict', rs) }}"
  tags:
    - bird-config
    
- name: Drop bird bgp static routes
  template:
    src: bgp-static-conf.j2
    dest: "/etc/bgp-static.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  register: bird_results_static
  loop: "{{ query('dict', routes) }}"
  tags:
    - bird-config

- name: Drop include configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  register: bird_results_includes
  loop: 
    - { src: 'bird-bgp-clients.j2', dest: '/etc/bird.bgp.clients' }
    - { src: 'ipv4-filters-conf.j2', dest: '/etc/ipv4.filters' }
  
  tags:
    - bird-config

- name: Restart bird services
  service:
    name: "{{ item.item.service }}"
    state: restarted
  when: "item is changed"
  ignore_errors: "{{ ansible_check_mode | default(false) }}"
  loop: "{{ bird_results.results }}"
  tags:
    - upstart-init
    - bird-init

- name: Restart bird services after includes
  service:
    name: "bird"
    state: restarted
  when: "item is changed"
  ignore_errors: "{{ ansible_check_mode | default(false) }}"
  loop: "{{ bird_results_includes.results }}"
  tags:
    - upstart-init
    - bird-init

- name: Restart bird services after static routes
  service:
    name: "bird"
    state: restarted
  when: "item is changed"
  ignore_errors: "{{ ansible_check_mode | default(false) }}"
  loop: "{{ bird_results_static.results }}"
  tags:
    - upstart-init
    - bird-init  

- name: Disable inactive BIRD BGP services and remove from bootup start
  service:
    name: "{{ item.service }}"
    enabled: false
    state: stopped
  when:
    - "not item.enabled | bool"
    - "item.enabled != 'skip'"
  loop: "{{ bird_configs }}"
  ignore_errors: "{{ ansible_check_mode | default(false) }}"
  tags:
    - upstart-init
    - bird-init

- name: Start active BIRD BGP services and add to bootup start
  service:
    name: "{{ item.service }}"
    enabled: true
    state: started
  when:
    - "item.enabled | bool"
    - "item.enabled != 'skip'"
  loop: "{{ bird_configs }}"
  ignore_errors: "{{ ansible_check_mode | default(false) }}"
  tags:
    - upstart-init
    - bird-init

- name: Disable inactive firewalld services and remove from bootup start
  systemd: 
    name: firewalld 
    enabled: false
    state: stopped
  when:
    - "not enable_firewalld | bool"
  ignore_errors: "{{ ansible_check_mode | default(false) }}"
  tags:
    - upstart-init
    - bird-init

- name: Enable firewalld services and add to bootup start
  systemd: 
    name: firewalld 
    enabled: true
  when:
    - "enable_firewalld | bool"
  ignore_errors: "{{ ansible_check_mode | default(false) }}"
  tags:
    - upstart-init
    - bird-init

- name: Add BGP TCP firewall rules
  firewalld:
    source: "{{ item }}"
    port: 179/tcp
    permanent: true
    state: enabled
  with_items:
    - "{{ bgp_local_cidr }}"

- name: Add BGP UDP firewall rules
  firewalld:
    source: "{{ item }}"
    port: 179/tcp
    permanent: true
    state: enabled
  with_items:
    - "{{ bgp_local_cidr }}"

- name: Start active firewalld services and add to bootup start
  service:
    name: firewalld
    enabled: true
    state: started
  when:
    - "enable_firewalld | bool"
  ignore_errors: "{{ ansible_check_mode | default(false) }}"
  tags:
    - upstart-init
    - bird-init

- include_tasks: bird_security.yml

- name: Reload firewalld as a last check
  command: /bin/firewall-cmd --reload
  become: yes
  when:
    - "enable_firewalld | bool"
    