---
# Copyright 2019, Internet Solutions.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include_tasks: bird_security.yml

- name: Set fact for automatically enabling networks (IPv4)
  set_fact:
    bird_ipv4_enabled: "{{ ansible_default_ipv4 is defined | bool }}"
  when:
    - "bird_ipv4_enabled == 'detect'"
  tags:
    - bird-config
    - bird-init

- name: Ensure log file exists and is owned correctly
  file:
    path: "{{ bird_syslog_location }}"
    owner: bird
    group: bird
    mode: '0664'
    state: touch
  tags:
    - bird-config

- name: Ensure "{{ bird_conf_dir }}" directory exists
  file:
    dest: /etc/bird
    state: directory
    owner: bird
    group: bird

- name: Ensure "{{ bird_conf_dir }}/peers" directory exists
  file:
    dest: /etc/bird/peers
    state: directory
    owner: bird
    group: bird

- name: Ensure "{{ bird_conf_dir }}/templates" directory exists
  file:
    dest: /etc/bird/templates
    state: directory
    owner: bird
    group: bird

- name: Drop configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: 
    - { src: 'bird-functions.conf.j2', dest: '/etc/bird/functions.conf' }
    - { src: 'bird-filters.conf.j2', dest: '/etc/bird/filters.conf' }
    - { src: 'bird-service.j2', dest: '/usr/lib/systemd/system/bird.service' }
    - { src: 'bird-conf.j2', dest: '/etc/bird/bird.conf' }
  notify: restart bird
  tags:
    - bird-config

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start active firewalld services and add to bootup start
  service:
    name: "{{ item.service }}"
    enabled: true
    state: started
  loop:
    - { service: firewalld }
    - { service: bird }
  tags:
    - upstart-init
    - bird-init

- name: Add Firewall rules
  firewalld:
    port: '{{ item }}'
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "179/tcp"
    - "179/udp"

