---
- name: Converge
  hosts: instance1
  roles:
    - role: "{{ playbook_dir | dirname | dirname | basename }}"
      enable_firewalld: true
      bird_bgp_rr_enabled: true
      bird_bgp_rs_enabled: false
      bird_bgp_static_enabled: true
      bird_password_enabled: true
    - role: '~/.ansible/roles/ansible-logrotate'
      logrotate_scripts:
        - name: bird-logrotate
          path: /var/log/bird.log
          options:
            - daily
            - weekly
            - size 25M
            - rotate 7
            - missingok
            - compress
            - delaycompress
            - copytruncate
  vars:
    rr_ipv4:
      172.200.0.0:
        bird_friendly_name: "bird_rr_ipv4" # Ensure the friendly name uses lowercase and underscores to create long names #
        bird_local_as_ipv4: 65000 # Used to override the template import
        bird_neighbor_ipaddress_ipv4: 172.17.0.3 # Only internal neighbor can be RR client #
        bird_neighbor_as_ipv4: 65000 # ASN needs to be the same ASN as the peer to act as a RR client #
    rr_ipv6:
      2001:db8:1::242:ac11:2:
        bird_friendly_name: "bird_rr_ipv6" # Ensure the friendly name uses lowercase and underscores to create long names #
        bird_local_as_ipv6: 65000 # Used to override the template import
        bird_neighbor_ipaddress_ipv6: "2001:db8:1::242:ac11:3" # Only internal neighbor can be RR client #
        bird_neighbor_as_ipv6: 65000 # ASN needs to be the same ASN as the peer to act as a RR client #
  post_tasks:
    - name: Check bird is running
      command: pgrep -a bird
      register: bird_proc
      changed_when: false
    - name: Verify BIRD daemon operation
      command: birdc show status
      register: bird_health
      changed_when: false
    - name: Check role functions
      assert:
        that:
          - "'Daemon is up and running' in bird_health.stdout"

- hosts: instance2
  roles:
    - role: "{{ playbook_dir | dirname | dirname | basename }}"
      enable_firewalld: true
      bird_bgp_rr_enabled: true
      bird_bgp_rs_enabled: false
      bird_bgp_static_enabled: false
      bird_password_enabled: true
    - role: '~/.ansible/roles/ansible-logrotate'
      logrotate_scripts:
        - name: bird-logrotate
          path: /var/log/bird.log
          options:
            - daily
            - weekly
            - size 25M
            - rotate 7
            - missingok
            - compress
            - delaycompress
            - copytruncate
  vars:
    rr_ipv4:
      172.200.0.0:
        bird_friendly_name: "bird_rr_ipv4" # Ensure the friendly name uses lowercase and underscores to create long names #
        bird_local_as_ipv4: 65000 # Used to override the template import
        bird_neighbor_ipaddress_ipv4: 172.17.0.2 # Only internal neighbor can be RR client #
        bird_neighbor_as_ipv4: 65000 # ASN needs to be the same ASN as the peer to act as a RR client #
    rr_ipv6:
      2001:db8:1::242:ac11:2:
        bird_friendly_name: "bird_rr_ipv6" # Ensure the friendly name uses lowercase and underscores to create long names #
        bird_local_as_ipv6: 65000 # Used to override the template import
        bird_neighbor_ipaddress_ipv6: "2001:db8:1::242:ac11:2" # Only internal neighbor can be RR client #
        bird_neighbor_as_ipv6: 65000 # ASN needs to be the same ASN as the peer to act as a RR client #
  post_tasks:
    - name: Check bird is running
      command: pgrep -a bird
      register: bird_proc
      changed_when: false
    - name: Verify BIRD daemon operation
      command: birdc show status
      register: bird_health
      changed_when: false
    - name: Check role functions
      assert:
        that:
          - "'Daemon is up and running' in bird_health.stdout"
    # The following block will only work if the first node has started correctly #
    - name: Wait a few seconds for BGP to stablize
      wait_for:
        timeout: 10
    - name: Verify BIRD protocol operation
      command: birdc show protocols
      register: bird_protocols
    - name: Check role functions
      assert:
        that:
          - "'Established' in bird_protocols.stdout"