---
- name: Converge
  hosts: all
  roles:
    - role: "{{ playbook_dir | dirname | dirname | basename }}"
      bird_bgp_description_1: "Testing 1"
      bird_local_as_1: "65000"
      bird_cidr_1: "172.20.32.0/24"
      bird_neighbor_address_1: "172.20.32.1"
      bird_neighbor_as_1: "65001"
      bird_bgp_description_2: "Testing 2"
      bird_local_as_2: "65002"
      bird_cidr_2: "172.20.40.0/21"
      bird_neighbor_address_2: "172.20.40.1"
      bird_neighbor_as_2: "65001"
  post_tasks:
    - name: Check bird is running
      command: pgrep -a bird
      register: bird_proc
      changed_when: false
    - name: Verify BIRD daemon operation
      command: birdc show status
      register: bird_health
      changed_when: false
    - name: Check role functions
      assert:
        that:
          - "'Daemon is up and running' in bird_health.stdout"
