---
- name: Converge
  hosts: all
  roles:
    - role: "{{ playbook_dir | dirname | dirname | basename }}"
      bird_bgp_rr_enabled: true
      bird_bgp_rs_enabled: true
      bird_bgp_static_enabled: true
      bird_ipv4_includes:
        - bird.ipv4.filters
        - bird.bgp.rr.template
        - bird.bgp.rs.template
        - bird.bgp.clients
    - role: '~/.ansible/roles/ansible-logrotate'
      logrotate_scripts:
        - name: bird-logrotate
          path: /var/log/bird.log
          options:
            - daily
            - weekly
            - size 25M
            - rotate 7
            - missingok
            - compress
            - delaycompress
            - copytruncate
  vars:
    rr:
      172.17.0.0:
        bird_friendly_name: "bird_rr"
        bird_neighbor_ipaddress: "{{ bird_router_id }}"
        bird_neighbor_asn: 65000
        bird_cluster_id: "1.0.0.1"
    rs:
      172.18.0.0:
        bird_friendly_name: "bird_rs"
        bird_neighbor_ipaddress: 172.18.0.1
        bird_neighbor_asn: 65001
    static:
      172.19.0.0:
        bird_friendly_name: "bird_static"
        ipaddress: 172.19.0.0
        subnet: 255.255.255.0
        bird_neighbor_ipaddress: "{{ bird_router_id }}"

  post_tasks:
    - name: Check bird is running
      command: pgrep -a bird
      register: bird_proc
      changed_when: false
    - name: Verify BIRD daemon operation
      command: birdc show status
      register: bird_health
      changed_when: false
    - name: Check role functions
      assert:
        that:
          - "'Daemon is up and running' in bird_health.stdout"
