---
- name: Converge
  hosts: all
  roles:
    - role: "{{ playbook_dir | dirname | dirname | basename }}"
  vars:
    routes:
      172.20.33.0:
        ipaddress: 172.20.33.0
        subnet: 255.255.255.0
        gateway: 172.20.32.1
      172.20.34.0:
        ipaddress: 172.20.34.0
        subnet: 255.255.255.0
        gateway: 172.20.32.1  
  post_tasks:
    - name: Check bird is running
      command: pgrep -a bird
      register: bird_proc
      changed_when: false
    - name: Verify BIRD daemon operation
      command: birdc show status
      register: bird_health
      changed_when: false
    - name: Check role functions
      assert:
        that:
          - "'Daemon is up and running' in bird_health.stdout"
