---
- name: Converge
  hosts: all
  roles:
    - role: "{{ playbook_dir | dirname | dirname | basename }}"
      bird_protocols_bgp: |
        description "{{ ansible_default_ipv4['address'] }}";
        local as {{ bird_as_number }};
        neighbor {{ bird_neighbor_address }} as {{ bird_as_number }};
        multihop;
        rr client;
        graceful restart;
        import all;
        export all;
  post_tasks:
    - name: Check bird is running
      command: pgrep -a bird
      register: bird_proc
      changed_when: false
    - name: Verify BIRD daemon operation
      command: birdc show status
      register: bird_health
      changed_when: false
    - name: Check role functions
      assert:
        that:
          - "'Daemon is up and running' in bird_health.stdout"
